# Generated by Django 4.1.5 on 2023-05-18 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safezone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='regdate',
            field=models.DateField(default=datetime.date.today, verbose_name='등록날짜'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='제목'),
        ),
    ]
