# Generated by Django 4.1.5 on 2023-05-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safezone_app', '0002_alter_video_regdate_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='alarmmode',
            field=models.CharField(choices=[(1, 'SMS 문자메세지'), (2, '디스코드'), (3, '이메일')], max_length=20, verbose_name='알람 모드'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
