# Generated by Django 4.1.5 on 2023-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='management_locations',
            field=models.CharField(choices=[('option1', '구역 1'), ('option2', '구역 2'), ('option3', '구역 3'), ('option3', '구역 4'), ('option3', '구역 5'), ('option3', '구역 6'), ('option3', '구역 7'), ('option3', '구역 8'), ('option3', '구역 9')], max_length=100),
        ),
    ]
